language: node_js
env:
  global:
    - CXX=g++-4.8
cache: yarn
matrix:
  include:
    - node_js: "11"
    - node_js: "10"
      env: PUBLISH=true
    - node_js: "8"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
script:
  - yarn run ci
deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      tags: true
      all_branches: true
      condition: $PUBLISH = true
    skip_cleanup: true
notifications:
  email: false
